config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
  resources :posts
=======
>>>>>>> a5d0d164b69b74a6b48327d5fc3f099d774a13e3
  resources :topics
  resources :notes
  root 'home#home'
  
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  

end

app/models/note.rb
class Note < ActiveRecord::Base
    validates :title, presence: true
    validates :title, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
  
  def contact
  end
  
  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]
    
    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    
    redirect_to root_path
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
    @notes = Note.order('created_at DESC')
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :description)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post_id, :body)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
<<<<<<< HEAD
      params.require(:topic).permit(:title, :body)
=======
      params.require(:topic).permit(:title, :url)
>>>>>>> a5d0d164b69b74a6b48327d5fc3f099d774a13e3
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/home/contact.html.haml
%h1= t('.title')
%p1= t('.contact_us')

= form_tag request_contact_path, method: 'post' do
    = label_tag :name, t('.name')
    = text_field_tag :name, '', title: t('.enter_name'), size:50
    
    = label_tag :email, t('.email')
    = email_field_tag :email, '', title: t('.enter_email')
    
    = label_tag :telephone, t('.telephone')
    = telephone_field_tag :telephone, '', title: t('.enter_telephone')
    
    = label_tag :message, t('.message')
    = text_field_tag :message, '', title: t('.enter_message'), size: 100
    
    = submit_tag t('.submit')

app/views/home/home.html.haml
%h1= t('.title')
%p1= t('.welcome')

app/views/layouts/application.html.haml
!!!

%html
  %head
    %meta{'charset' => 'utf-8'}
    %meta{'http-equiv' => 'x-ua-compatible', 'content' => 'ie=edge'}

    %title= t('app_title')

    %meta{'name' => 'description', 'content' => t('app_description')}
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'modernizr'
    = csrf_meta_tags

  %body

  - flash.each do |key, value|
    = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?

  =render 'shared/header'
  
  = yield

  =render 'shared/footer'

app/views/notes/_form.html.haml
= form_for @note do |f|
  - if @note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/notes/edit.html.haml
%h1 Editing note

= render 'form'

= link_to 'Show', @note
\|
= link_to 'Back', notes_path

app/views/notes/index.html.haml
%h1 Listing notes

%table
  %thead
    %tr
      %th Date
      %th Title
      %th Description
      %th
      %th
      %th

  %tbody
    - @notes.each do |note|
      %tr
        %td= note.created_at.strftime("%d-%m-%Y")
        %td= note.title
        %td= note.description
        %td= link_to 'Show', note
        %td= link_to 'Edit', edit_note_path(note)
        %td= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Note', new_note_path

app/views/notes/new.html.haml
%h1 New note

= render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.haml
%p#notice= notice
%p
  %b Date:
  = @note.created_at
%p
  %b Title:
  = @note.title
%p
  %b Description:
  = @note.description

= link_to 'Edit', edit_note_path(@note)
\|
= link_to 'Back', notes_path

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :post_id
    = f.number_field :post_id
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Post
      %th Body
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.post_id
        %td= post.body
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Post:
  = @post.post_id
%p
  %b Body:
  = @post.body

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/shared/_footer.html.haml
%footer
    %p!=  "My Website #{Time.now.year}"

app/views/shared/_header.html.haml
%header
    %h1 Welcome to My Notes Application
    
=link_to "Home", root_path
=link_to "Contact Us", "/contact"
=link_to "Notes", "/notes"

app/views/topics/_form.html.haml
= form_for @topic do |f|
  - if @topic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
      %ul
        - @topic.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
<<<<<<< HEAD
    = f.label :body
    = f.text_area :body
=======
    = f.label :url
    = f.text_field :url
>>>>>>> a5d0d164b69b74a6b48327d5fc3f099d774a13e3
  .actions
    = f.submit 'Save'

app/views/topics/edit.html.haml
%h1 Editing topic

= render 'form'

= link_to 'Show', @topic
\|
= link_to 'Back', topics_path

app/views/topics/index.html.haml
%h1 Listing topics

%table
  %thead
    %tr
      %th Title
<<<<<<< HEAD
      %th Body
=======
      %th Url
>>>>>>> a5d0d164b69b74a6b48327d5fc3f099d774a13e3
      %th
      %th
      %th

  %tbody
    - @topics.each do |topic|
      %tr
        %td= topic.title
<<<<<<< HEAD
        %td= topic.body
=======
        %td= topic.url
>>>>>>> a5d0d164b69b74a6b48327d5fc3f099d774a13e3
        %td= link_to 'Show', topic
        %td= link_to 'Edit', edit_topic_path(topic)
        %td= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Topic', new_topic_path

app/views/topics/new.html.haml
%h1 New topic

= render 'form'

= link_to 'Back', topics_path

app/views/topics/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @topic.title
%p
<<<<<<< HEAD
  %b Body:
  = @topic.body
=======
  %b Url:
  = @topic.url
>>>>>>> a5d0d164b69b74a6b48327d5fc3f099d774a13e3

= link_to 'Edit', edit_topic_path(@topic)
\|
= link_to 'Back', topics_path